"""Unit content: the lesson and item sets for each unit, generated by Claude and reviewed (P5.1).

Lessons and item sets are generated once per (unit, kind, variant) and cached by `units`. Item sets
go through the drills' two-pass approach: generate, then an independent review re-solves every
item, fixing wrong keys and dropping doubtful items. `seed_demo` writes hand-written, checked
content for the first unit so pages and the player work without Claude.
"""

import re
from typing import Literal

from pydantic import BaseModel, Field
from sqlmodel import Session, col, select

from app.models import ExerciseAttempt, Unit
from app.services.cards import fix_latin_accents
from app.services.claude import ClaudeClient, Task
from app.services.drill_player import norm
from app.services.exercises import ItemSet, parse_items
from app.services.weakness import topic_label

DEMO_UNIT = "u01-where-you-are"
NO_DASH = ("Punctuation: never use em dashes in English text; use commas, colons or full stops. Inside Russian "
           "sentences keep a dash only where Russian grammar requires it.")
STRESS_RULE = ("Put a stress mark (U+0301 COMBINING ACUTE ACCENT, directly after the stressed vowel) on every Russian "
               "word of two or more syllables; never on ё or one-syllable words. Never use Latin accented letters.")
LEARNER = ("an English-speaking adult at intermediate (B1) level preparing for a family trip to Moscow; "
           "explanations in plain English, examples from real travel and family situations")


def _unit_brief(unit: Unit) -> str:
    topics = ", ".join(topic_label(t) for t in unit.topics_json or []) or "general"
    return (f"Unit: {unit.title} (level {unit.level}).\nGrammar topics: {topics}.\nVocabulary theme: {unit.vocab_theme}.\n"
            f"Can-do goal: {unit.can_do}")


def _client(session: Session, client):
    return client or ClaudeClient(session)


def _fix(value):
    """Latin accented letters to Cyrillic + U+0301, recursively."""
    if isinstance(value, str):
        return fix_latin_accents(value)
    if isinstance(value, list):
        return [_fix(v) for v in value]
    if isinstance(value, dict):
        return {k: _fix(v) for k, v in value.items()}
    return value


# --- Lessons ------------------------------------------------------------------------------------

LESSON_SYSTEM = f"""You write short grammar lessons for {LEARNER}.

A lesson teaches exactly one pattern, the unit's topic, and nothing else:
- intro: two or three sentences on why this matters on the trip.
- rule_points: 3-5 short English points, each one rule or form with a Russian example in «guillemets».
- examples: 4-6 natural, everyday sentences showing the pattern, each with an English translation.
- notice_ru: a short connected text (3-4 sentences) using the pattern several times; notice_task tells the learner what to spot in it.
- words: 10-15 words or short phrases for the vocabulary theme that the learner will need with this pattern.
All Russian must be correct, natural modern Russian. {STRESS_RULE}
{NO_DASH}"""


def generate_lesson(session: Session, unit: Unit, client=None):
    from app.services.units import Lesson
    lesson = _client(session, client).ask_structured(Task.drill_generation, LESSON_SYSTEM, _unit_brief(unit), Lesson, max_tokens=6000)
    return Lesson(**_fix(lesson.model_dump()))


# --- Item sets ------------------------------------------------------------------------------------

class Pair(BaseModel):
    left: str
    right: str


class GenItem(BaseModel):
    """Flat shape for generation; converted into the typed item models afterwards."""
    type: Literal["choice", "fill", "match", "transform", "build", "translate", "listen_choice", "dictation"]
    instruction: str = Field(default="", description="One short English line telling the learner what to do")
    explanation: str = Field(description="One or two English sentences: the rule behind the answer")
    question_ru: str = Field(default="", description="choice: the Russian sentence, ___ for the gap if any")
    question_en: str = Field(default="", description="choice: English meaning; listen_choice: the English question")
    options: list[str] = Field(default_factory=list, description="choice: 3-4 Russian options; listen_choice: 3-4 English options")
    answer_index: int = Field(default=0, description="choice and listen_choice: index of the right option")
    prompt_ru: str = Field(default="", description="fill: one sentence with exactly one ___")
    cue: str = Field(default="", description="fill: the dictionary form or the choice, never the answer")
    translation_en: str = Field(default="", description="fill and dictation: English translation")
    answer: str = Field(default="", description="fill, transform, build, translate: the correct answer")
    accepted: list[str] = Field(default_factory=list, description="Other fully correct answers")
    pairs: list[Pair] = Field(default_factory=list, description="match: 3-6 pairs")
    source_ru: str = Field(default="", description="transform: the sentence to change")
    task: str = Field(default="", description="transform: what to change, in English")
    meaning_en: str = Field(default="", description="build: the meaning of the sentence to assemble")
    tiles: list[str] = Field(default_factory=list, description="build: the words of the answer in answer order")
    en: str = Field(default="", description="translate: the English sentence")
    audio_ru: str = Field(default="", description="listen_choice and dictation: the Russian sentence that is spoken")


class GenSet(BaseModel):
    title: str
    intro: str = Field(default="", description="Remediation only: a fresh explanation of the rule from a different angle, 3-5 sentences")
    items: list[GenItem]


class ItemVerdict(BaseModel):
    index: int
    solved: str = Field(description="Your own answer, worked out before looking at the key")
    verdict: Literal["ok", "fix", "drop"]
    answer: str = Field(default="", description="fix: the correct answer (for choice types, the correct option text)")
    accepted: list[str] = Field(default_factory=list)
    note: str = ""


class ItemReview(BaseModel):
    items: list[ItemVerdict]


PLANS = {
    "pretest": ("Pre-test", 6, "choice, fill and translate; quick checks of the core forms, no listening"),
    "practice": ("Practice", 8, "a mix: about 2 choice, 2 fill, 1 match, 1 transform, 1 build, 1 translate; easiest first"),
    "listening": ("Listening", 6, "3 listen_choice then 3 dictation; short sentences (under 10 words) built on the pattern"),
    "quiz": ("Quiz", 12, "every type at least once (choice, fill, match, transform, build, translate, listen_choice, dictation); harder than practice; new sentences"),
    "remediation": ("Remediation", 8, "targets exactly the mistakes listed below with fill, choice and transform items; plus an intro that explains the rule from a different angle than a textbook would"),
    "revisit": ("Review", 8, "mixed types including one listen_choice; a quick check that the topic has stuck"),
}
MIN_ITEMS = {"pretest": 4, "practice": 5, "listening": 4, "quiz": 8, "remediation": 5, "revisit": 5}

ITEMS_SYSTEM = f"""You write exercises for {LEARNER}. Every item practises the unit's grammar topic with the unit's vocabulary theme.

Item types and the fields each uses:
- choice: question_ru (with ___ when there is a gap), question_en, options (3-4 Russian options; distractors are the errors learners really make, such as the wrong case ending), answer_index.
- fill: prompt_ru with exactly one ___, cue (dictionary form, never the answer), translation_en, answer, accepted.
- match: pairs (3-6, e.g. a noun and its form after в or на), instruction.
- transform: source_ru, task (what to change, in English), answer, accepted.
- build: meaning_en, tiles (the answer's words in order, punctuation attached to the last word), answer.
- translate: en (one short sentence), answer, accepted (every other natural correct translation).
- listen_choice: audio_ru (spoken, under 10 words), question_en, options (English), answer_index.
- dictation: audio_ru (under 8 words), translation_en.
Every item has an explanation naming the rule. Each item has exactly one correct answer (list true alternatives in accepted). Vary the words and situations; never reuse a sentence. All Russian correct and natural. {STRESS_RULE}
{NO_DASH}"""

REVIEW_SYSTEM = """You are a meticulous Russian checker reviewing exercises before a learner sees them. For each item, solve it yourself first and write your answer in `solved`, then compare with the key.
- ok: the key is correct and the item has one clear answer (or every alternative is listed).
- fix: the item is good but the key is wrong or misses a correct alternative; give the correct answer (for choice types, the correct option's text) and the full accepted list.
- drop: ambiguous, unnatural, off-topic, the cue gives the answer away, a build whose tiles don't make the answer, or Russian that isn't correct.
Treat ё/е and missing stress marks as equivalent. Dropping a doubtful item is better than teaching a wrong form."""


def _missed(session: Session, unit: Unit) -> list[str]:
    rows = session.exec(select(ExerciseAttempt).where(
        ExerciseAttempt.unit_id == unit.id, ExerciseAttempt.correct == False,  # noqa: E712
        col(ExerciseAttempt.kind).in_(["quiz", "practice", "revisit"])).order_by(col(ExerciseAttempt.created_at).desc())).all()
    return [f"{a.item_type}: answered «{a.answer}»" for a in rows[:12]]


def _prompt(session: Session, unit: Unit, kind: str, variant: int) -> str:
    title, n, mix = PLANS[kind]
    extra = ""
    if kind == "remediation":
        missed = _missed(session, unit)
        extra = "\nThe learner's recent wrong answers:\n" + ("\n".join(f"- {m}" for m in missed) or "- none recorded")
    if variant:
        extra += f"\nThis is variant {variant + 1}: use different sentences and words from earlier sets."
    return f"{_unit_brief(unit)}\n\nWrite a {title.lower()} set of {n} items: {mix}.{extra}"


def _to_item(g: GenItem, idx: int, topic: str) -> dict | None:
    d = {k: v for k, v in g.model_dump().items() if v not in ("", [], None)}
    d["answer_index"] = g.answer_index
    d.update(id=f"i{idx + 1}", topic=topic)
    try:
        return parse_items([d])[0].model_dump()
    except Exception:
        return None


def _bare(text: str) -> str:
    return re.sub(r"[.!?]+$", "", norm(text))


def _valid(item: dict) -> bool:
    t = item["type"]
    if t == "fill":
        return item["prompt_ru"].count("___") == 1 and bool(item["answer"].strip())
    if t in ("choice", "listen_choice"):
        ok = 2 <= len(item["options"]) <= 5 and 0 <= item["answer_index"] < len(item["options"])
        return ok and (t == "choice" or bool(item["audio_ru"].strip()))
    if t == "match":
        return 3 <= len(item["pairs"]) <= 6
    if t == "build":
        return len(item["tiles"]) >= 2 and _bare(" ".join(item["tiles"])) == _bare(item["answer"])
    if t == "dictation":
        return bool(item["audio_ru"].strip())
    return bool(item.get("answer", "").strip())


def _key(item: dict) -> str:
    t = item["type"]
    if t in ("choice", "listen_choice"):
        return item["options"][item["answer_index"]]
    if t == "match":
        return "; ".join(f"{p['left']} = {p['right']}" for p in item["pairs"])
    if t == "dictation":
        return item["audio_ru"]
    return item.get("answer", "")


def _describe(i: int, item: dict) -> str:
    fields = {k: v for k, v in item.items() if k not in ("id", "topic", "skill", "explanation", "instruction")}
    return f"{i}. {fields}\n   key: {_key(item)}"


def _review(client, items: list[dict]) -> list[dict]:
    listing = "\n".join(_describe(i, it) for i, it in enumerate(items))
    review = client.ask_structured(Task.drill_review, REVIEW_SYSTEM, f"Review these {len(items)} items:\n\n{listing}", ItemReview, max_tokens=8000)
    verdicts = {v.index: v for v in review.items}
    kept = []
    for i, item in enumerate(items):
        v = verdicts.get(i)
        if v is None or v.verdict == "drop":
            continue
        if v.verdict == "fix":
            t = item["type"]
            if t in ("choice", "listen_choice"):
                fixed = next((k for k, o in enumerate(item["options"]) if norm(o) == norm(v.answer)), None)
                if fixed is None:
                    continue
                item = {**item, "answer_index": fixed}
            elif t in ("match", "build"):
                continue  # structure can't be repaired safely
            elif t == "dictation":
                item = {**item, "accepted": v.accepted}
            else:
                item = {**item, "answer": v.answer or item.get("answer", ""), "accepted": v.accepted}
        kept.append(item)
    return kept


def generate_items(session: Session, unit: Unit, kind: str, variant: int, client=None) -> ItemSet:
    from app.services.drills import NotEnoughItems
    client = _client(session, client)
    gen = client.ask_structured(Task.drill_generation, ITEMS_SYSTEM, _prompt(session, unit, kind, variant), GenSet, max_tokens=12000)
    topic = (unit.topics_json or [""])[0]
    items = [d for d in (_to_item(g, i, topic) for i, g in enumerate(gen.items)) if d is not None and _valid(d)]
    if kind == "pretest":
        items = [d for d in items if d["type"] not in ("listen_choice", "dictation")]
    items = _review(client, items)
    if len(items) < MIN_ITEMS[kind]:
        raise NotEnoughItems(f"Only {len(items)} items passed the check; try again.")
    title = PLANS[kind][0] if kind != "practice" else f"Practice {variant + 1}"
    return ItemSet(**_fix({"title": title, "intro": gen.intro if kind == "remediation" else "", "items": items}))


P = "/grammar/cases#prepositional"
L = "/grammar/cases#prepositional-locative"

DEMO = {
    ("lesson", 0): {
        "title": "Where you are: в and на + prepositional",
        "intro": "Most travel sentences say where something is: at the station, in the hotel, on the square. Russian marks this with в or на and the prepositional case.",
        "rule_points": [
            "«в» is in or at an enclosed place: в гости́нице, в музе́е, в апте́ке.",
            "«на» goes with open spaces, events and some fixed places: на вокза́ле, на пло́щади, на у́лице, на рабо́те.",
            "The prepositional ending is usually -е: вокза́л → на вокза́ле, Москва́ → в Москве́.",
            "Nouns in -ия and soft-sign feminine nouns take -и: ста́нция → на ста́нции, пло́щадь → на пло́щади.",
            "A few masculine nouns take a stressed -у́ after в and на: в аэропорту́, в саду́.",
        ],
        "examples": [
            {"ru": "Мы в гости́нице.", "en": "We're at the hotel."},
            {"ru": "Он на вокза́ле.", "en": "He's at the station."},
            {"ru": "Я в аэропорту́.", "en": "I'm at the airport."},
            {"ru": "Апте́ка на пло́щади.", "en": "The pharmacy is on the square."},
            {"ru": "Мы живём в Москве́.", "en": "We live in Moscow."},
        ],
        "notice_ru": "Сейча́с я на вокза́ле. Мой брат в гости́нице, а сестра́ ещё в аэропорту́. Встре́тимся на пло́щади у музе́я.",
        "notice_task": "Find every place after в or на and look at its ending.",
        "words": [
            {"ru": "вокза́л", "en": "railway station"}, {"ru": "гости́ница", "en": "hotel"},
            {"ru": "аэропо́рт", "en": "airport"}, {"ru": "пло́щадь", "en": "square"},
            {"ru": "у́лица", "en": "street"}, {"ru": "апте́ка", "en": "pharmacy"},
            {"ru": "музе́й", "en": "museum"}, {"ru": "ры́нок", "en": "market"},
            {"ru": "ста́нция метро́", "en": "metro station"}, {"ru": "магази́н", "en": "shop"},
            {"ru": "рабо́та", "en": "work"}, {"ru": "парк", "en": "park"},
        ],
    },
    ("pretest", 0): {"title": "Pre-test", "items": [
        {"id": "p1", "type": "choice", "topic": P, "question_ru": "Мы ___ гости́нице.", "question_en": "We're at the hotel.", "options": ["в", "на", "у"], "answer_index": 0, "explanation": "A hotel is an enclosed place: в гости́нице."},
        {"id": "p2", "type": "choice", "topic": P, "question_ru": "Он ждёт на ___.", "question_en": "He's waiting at the station.", "options": ["вокза́л", "вокза́ле", "вокза́ла"], "answer_index": 1, "explanation": "After на for location, the prepositional: на вокза́ле."},
        {"id": "p3", "type": "fill", "topic": L, "prompt_ru": "Я сейча́с в ___.", "cue": "аэропо́рт", "translation_en": "I'm at the airport now.", "answer": "аэропорту́", "explanation": "аэропо́рт takes the stressed -у́ after в: в аэропорту́."},
        {"id": "p4", "type": "fill", "topic": P, "prompt_ru": "Апте́ка на ___.", "cue": "пло́щадь", "translation_en": "The pharmacy is on the square.", "answer": "пло́щади", "explanation": "Soft-sign feminine nouns take -и: на пло́щади."},
        {"id": "p5", "type": "choice", "topic": P, "question_ru": "Мы живём в ___.", "question_en": "We live in Moscow.", "options": ["Москва́", "Москве́", "Москву́"], "answer_index": 1, "explanation": "в + prepositional for where: в Москве́."},
        {"id": "p6", "type": "translate", "topic": P, "en": "I'm at the museum.", "answer": "Я в музе́е.", "accepted": ["Я сейча́с в музе́е."], "explanation": "в музе́е: -ей nouns take -е."},
    ]},
    ("practice", 0): {"title": "Practice 1", "items": [
        {"id": "q1", "type": "choice", "topic": P, "question_ru": "Где ты? Я ___ ста́нции метро́.", "options": ["в", "на"], "answer_index": 1, "explanation": "Stations go with на: на ста́нции, на вокза́ле."},
        {"id": "q2", "type": "fill", "topic": P, "prompt_ru": "Мой брат рабо́тает в ___.", "cue": "банк", "translation_en": "My brother works at a bank.", "answer": "ба́нке", "explanation": "в + prepositional: в ба́нке."},
        {"id": "q3", "type": "match", "topic": P, "instruction": "Match each place to 'at/in' it.", "pairs": [
            {"left": "вокза́л", "right": "на вокза́ле"}, {"left": "гости́ница", "right": "в гости́нице"},
            {"left": "пло́щадь", "right": "на пло́щади"}, {"left": "аэропо́рт", "right": "в аэропорту́"}], "explanation": "Each place keeps its own preposition: на for stations and squares, в for buildings."},
        {"id": "q4", "type": "transform", "topic": P, "source_ru": "Я иду́ в музе́й.", "task": "Say you are already at the museum.", "answer": "Я в музе́е.", "accepted": ["Я уже́ в музе́е."], "explanation": "Going there takes the accusative (в музе́й); being there takes the prepositional (в музе́е)."},
        {"id": "q5", "type": "build", "topic": P, "meaning_en": "The shop is on the street.", "tiles": ["Магази́н", "на", "у́лице."], "answer": "Магази́н на у́лице.", "explanation": "на у́лице: streets go with на."},
        {"id": "q6", "type": "translate", "topic": P, "en": "We are at the market.", "answer": "Мы на ры́нке.", "explanation": "Markets go with на: на ры́нке."},
        {"id": "q7", "type": "fill", "topic": P, "prompt_ru": "Встре́тимся в ___.", "cue": "парк", "translation_en": "Let's meet in the park.", "answer": "па́рке", "explanation": "в па́рке: the prepositional ending -е."},
        {"id": "q8", "type": "choice", "topic": P, "question_ru": "Она́ сейча́с ___ рабо́те.", "question_en": "She's at work now.", "options": ["в", "на"], "answer_index": 1, "explanation": "Work takes на: на рабо́те."},
    ]},
    ("practice", 1): {"title": "Practice 2", "items": [
        {"id": "r1", "type": "fill", "topic": P, "prompt_ru": "Ключи́ в ___.", "cue": "гости́ница", "translation_en": "The keys are at the hotel.", "answer": "гости́нице", "explanation": "-а nouns take -е: в гости́нице."},
        {"id": "r2", "type": "choice", "topic": P, "question_ru": "Мы бы́ли ___ конце́рте.", "question_en": "We were at a concert.", "options": ["в", "на"], "answer_index": 1, "explanation": "Events take на: на конце́рте, на вы́ставке."},
        {"id": "r3", "type": "fill", "topic": P, "prompt_ru": "Он живёт в ___.", "cue": "Петербу́рг", "translation_en": "He lives in Petersburg.", "answer": "Петербу́рге", "explanation": "Cities take в + prepositional: в Петербу́рге."},
        {"id": "r4", "type": "transform", "topic": P, "source_ru": "Я в гости́нице.", "task": "Say it about the railway station instead.", "answer": "Я на вокза́ле.", "explanation": "The station takes на, and вокза́л becomes вокза́ле."},
        {"id": "r5", "type": "build", "topic": L, "meaning_en": "My sister is still at the airport.", "tiles": ["Моя́", "сестра́", "ещё", "в", "аэропорту́."], "answer": "Моя́ сестра́ ещё в аэропорту́.", "explanation": "в аэропорту́, with the stressed -у́."},
        {"id": "r6", "type": "choice", "topic": P, "question_ru": "Где апте́ка?", "question_en": "Pick the natural answer.", "options": ["На у́лице Арба́т.", "В у́лица Арба́т.", "На у́лицу Арба́т."], "answer_index": 0, "explanation": "Location: на + prepositional, на у́лице."},
    ]},
    ("listening", 0): {"title": "Listening", "items": [
        {"id": "l1", "type": "listen_choice", "topic": P, "audio_ru": "Я жду вас на вокза́ле.", "question_en": "Where is the speaker waiting?", "options": ["At the station", "At the hotel", "At the airport"], "answer_index": 0, "explanation": "на вокза́ле: at the station."},
        {"id": "l2", "type": "listen_choice", "topic": L, "audio_ru": "Мы ещё в аэропорту́, бу́дем че́рез час.", "question_en": "Where are they now?", "options": ["At the airport", "On the square", "At home"], "answer_index": 0, "explanation": "в аэропорту́: at the airport."},
        {"id": "l3", "type": "dictation", "topic": P, "audio_ru": "Апте́ка на пло́щади.", "translation_en": "The pharmacy is on the square.", "explanation": "на пло́щади, with -и."},
        {"id": "l4", "type": "dictation", "topic": P, "audio_ru": "Мы в гости́нице.", "translation_en": "We're at the hotel.", "explanation": "в гости́нице, with -е."},
    ]},
    ("quiz", 0): {"title": "Quiz", "items": [
        {"id": "z1", "type": "choice", "topic": P, "question_ru": "Он ___ вокза́ле.", "options": ["в", "на"], "answer_index": 1, "explanation": "на вокза́ле."},
        {"id": "z2", "type": "fill", "topic": P, "prompt_ru": "Мы живём в ___.", "cue": "Москва́", "translation_en": "We live in Moscow.", "answer": "Москве́", "explanation": "в Москве́."},
        {"id": "z3", "type": "fill", "topic": L, "prompt_ru": "Я в ___.", "cue": "аэропо́рт", "translation_en": "I'm at the airport.", "answer": "аэропорту́", "explanation": "в аэропорту́, stressed -у́."},
        {"id": "z4", "type": "choice", "topic": P, "question_ru": "Па́па на ___.", "question_en": "Dad is at work.", "options": ["рабо́та", "рабо́те", "рабо́ту"], "answer_index": 1, "explanation": "на рабо́те: location, prepositional."},
        {"id": "z5", "type": "translate", "topic": P, "en": "The hotel is on the square.", "answer": "Гости́ница на пло́щади.", "explanation": "на пло́щади."},
        {"id": "z6", "type": "fill", "topic": P, "prompt_ru": "Встре́тимся на ___.", "cue": "ста́нция", "translation_en": "Let's meet at the station.", "answer": "ста́нции", "explanation": "-ия nouns take -и: на ста́нции."},
        {"id": "z7", "type": "transform", "topic": P, "source_ru": "Я иду́ на ры́нок.", "task": "Say you are already at the market.", "answer": "Я на ры́нке.", "accepted": ["Я уже́ на ры́нке."], "explanation": "на ры́нок (going) becomes на ры́нке (being there)."},
        {"id": "z8", "type": "match", "topic": P, "instruction": "Match each place to 'at/in' it.", "pairs": [
            {"left": "музе́й", "right": "в музе́е"}, {"left": "у́лица", "right": "на у́лице"}, {"left": "парк", "right": "в па́рке"}], "explanation": "в for buildings and parks, на for streets."},
        {"id": "z9", "type": "build", "topic": P, "meaning_en": "We are in the museum now.", "tiles": ["Мы", "сейча́с", "в", "музе́е."], "answer": "Мы сейча́с в музе́е.", "accepted": ["Сейча́с мы в музе́е."], "explanation": "в музе́е."},
        {"id": "z10", "type": "listen_choice", "topic": P, "audio_ru": "Она́ на рабо́те до шести́.", "question_en": "Where is she?", "options": ["At work", "At the market", "In the park"], "answer_index": 0, "explanation": "на рабо́те: at work."},
    ]},
}


def seed_demo(session: Session) -> None:
    """Store the hand-written content for the first unit (idempotent)."""
    from app.services import units

    for (kind, variant), body in DEMO.items():
        units.store(session, DEMO_UNIT, kind, variant, body)
