"""Unit content: the lesson and item sets for each unit, generated by Claude and reviewed (P5.1).

Generation is the orchestrator's (prompts, second-pass review). `seed_demo` writes hand-written,
checked content for the first unit so pages and the player can be built and tested without Claude.
"""

from sqlmodel import Session

from app.models import Unit
from app.services.exercises import ItemSet

DEMO_UNIT = "u01-where-you-are"


def generate_lesson(session: Session, unit: Unit, client=None):
    raise NotImplementedError("Lesson generation arrives with the unit engine (P5.1); use seed_demo for now")


def generate_items(session: Session, unit: Unit, kind: str, variant: int, client=None) -> ItemSet:
    raise NotImplementedError("Item generation arrives with the unit engine (P5.1); use seed_demo for now")


P = "/grammar/cases#prepositional"
L = "/grammar/cases#prepositional-locative"

DEMO = {
    ("lesson", 0): {
        "title": "Where you are: в and на + prepositional",
        "intro": "Most travel sentences say where something is: at the station, in the hotel, on the square. Russian marks this with в or на and the prepositional case.",
        "rule_points": [
            "«в» is in or at an enclosed place: в гости́нице, в музе́е, в апте́ке.",
            "«на» goes with open spaces, events and some fixed places: на вокза́ле, на пло́щади, на у́лице, на рабо́те.",
            "The prepositional ending is usually -е: вокза́л → на вокза́ле, Москва́ → в Москве́.",
            "Nouns in -ия and soft-sign feminine nouns take -и: ста́нция → на ста́нции, пло́щадь → на пло́щади.",
            "A few masculine nouns take a stressed -у́ after в and на: в аэропорту́, в саду́.",
        ],
        "examples": [
            {"ru": "Мы в гости́нице.", "en": "We're at the hotel."},
            {"ru": "Он на вокза́ле.", "en": "He's at the station."},
            {"ru": "Я в аэропорту́.", "en": "I'm at the airport."},
            {"ru": "Апте́ка на пло́щади.", "en": "The pharmacy is on the square."},
            {"ru": "Мы живём в Москве́.", "en": "We live in Moscow."},
        ],
        "notice_ru": "Сейча́с я на вокза́ле. Мой брат в гости́нице, а сестра́ ещё в аэропорту́. Встре́тимся на пло́щади у музе́я.",
        "notice_task": "Find every place after в or на and look at its ending.",
        "words": [
            {"ru": "вокза́л", "en": "railway station"}, {"ru": "гости́ница", "en": "hotel"},
            {"ru": "аэропо́рт", "en": "airport"}, {"ru": "пло́щадь", "en": "square"},
            {"ru": "у́лица", "en": "street"}, {"ru": "апте́ка", "en": "pharmacy"},
            {"ru": "музе́й", "en": "museum"}, {"ru": "ры́нок", "en": "market"},
            {"ru": "ста́нция метро́", "en": "metro station"}, {"ru": "магази́н", "en": "shop"},
            {"ru": "рабо́та", "en": "work"}, {"ru": "парк", "en": "park"},
        ],
    },
    ("pretest", 0): {"title": "Pre-test", "items": [
        {"id": "p1", "type": "choice", "topic": P, "question_ru": "Мы ___ гости́нице.", "question_en": "We're at the hotel.", "options": ["в", "на", "у"], "answer_index": 0, "explanation": "A hotel is an enclosed place: в гости́нице."},
        {"id": "p2", "type": "choice", "topic": P, "question_ru": "Он ждёт на ___.", "question_en": "He's waiting at the station.", "options": ["вокза́л", "вокза́ле", "вокза́ла"], "answer_index": 1, "explanation": "After на for location, the prepositional: на вокза́ле."},
        {"id": "p3", "type": "fill", "topic": L, "prompt_ru": "Я сейча́с в ___.", "cue": "аэропо́рт", "translation_en": "I'm at the airport now.", "answer": "аэропорту́", "explanation": "аэропо́рт takes the stressed -у́ after в: в аэропорту́."},
        {"id": "p4", "type": "fill", "topic": P, "prompt_ru": "Апте́ка на ___.", "cue": "пло́щадь", "translation_en": "The pharmacy is on the square.", "answer": "пло́щади", "explanation": "Soft-sign feminine nouns take -и: на пло́щади."},
        {"id": "p5", "type": "choice", "topic": P, "question_ru": "Мы живём в ___.", "question_en": "We live in Moscow.", "options": ["Москва́", "Москве́", "Москву́"], "answer_index": 1, "explanation": "в + prepositional for where: в Москве́."},
        {"id": "p6", "type": "translate", "topic": P, "en": "I'm at the museum.", "answer": "Я в музе́е.", "accepted": ["Я сейча́с в музе́е."], "explanation": "в музе́е: -ей nouns take -е."},
    ]},
    ("practice", 0): {"title": "Practice 1", "items": [
        {"id": "q1", "type": "choice", "topic": P, "question_ru": "Где ты? Я ___ ста́нции метро́.", "options": ["в", "на"], "answer_index": 1, "explanation": "Stations go with на: на ста́нции, на вокза́ле."},
        {"id": "q2", "type": "fill", "topic": P, "prompt_ru": "Мой брат рабо́тает в ___.", "cue": "банк", "translation_en": "My brother works at a bank.", "answer": "ба́нке", "explanation": "в + prepositional: в ба́нке."},
        {"id": "q3", "type": "match", "topic": P, "instruction": "Match each place to 'at/in' it.", "pairs": [
            {"left": "вокза́л", "right": "на вокза́ле"}, {"left": "гости́ница", "right": "в гости́нице"},
            {"left": "пло́щадь", "right": "на пло́щади"}, {"left": "аэропо́рт", "right": "в аэропорту́"}], "explanation": "Each place keeps its own preposition: на for stations and squares, в for buildings."},
        {"id": "q4", "type": "transform", "topic": P, "source_ru": "Я иду́ в музе́й.", "task": "Say you are already at the museum.", "answer": "Я в музе́е.", "accepted": ["Я уже́ в музе́е."], "explanation": "Going there takes the accusative (в музе́й); being there takes the prepositional (в музе́е)."},
        {"id": "q5", "type": "build", "topic": P, "meaning_en": "The shop is on the street.", "tiles": ["Магази́н", "на", "у́лице."], "answer": "Магази́н на у́лице.", "explanation": "на у́лице: streets go with на."},
        {"id": "q6", "type": "translate", "topic": P, "en": "We are at the market.", "answer": "Мы на ры́нке.", "explanation": "Markets go with на: на ры́нке."},
        {"id": "q7", "type": "fill", "topic": P, "prompt_ru": "Встре́тимся в ___.", "cue": "парк", "translation_en": "Let's meet in the park.", "answer": "па́рке", "explanation": "в па́рке: the prepositional ending -е."},
        {"id": "q8", "type": "choice", "topic": P, "question_ru": "Она́ сейча́с ___ рабо́те.", "question_en": "She's at work now.", "options": ["в", "на"], "answer_index": 1, "explanation": "Work takes на: на рабо́те."},
    ]},
    ("practice", 1): {"title": "Practice 2", "items": [
        {"id": "r1", "type": "fill", "topic": P, "prompt_ru": "Ключи́ в ___.", "cue": "гости́ница", "translation_en": "The keys are at the hotel.", "answer": "гости́нице", "explanation": "-а nouns take -е: в гости́нице."},
        {"id": "r2", "type": "choice", "topic": P, "question_ru": "Мы бы́ли ___ конце́рте.", "question_en": "We were at a concert.", "options": ["в", "на"], "answer_index": 1, "explanation": "Events take на: на конце́рте, на вы́ставке."},
        {"id": "r3", "type": "fill", "topic": P, "prompt_ru": "Он живёт в ___.", "cue": "Петербу́рг", "translation_en": "He lives in Petersburg.", "answer": "Петербу́рге", "explanation": "Cities take в + prepositional: в Петербу́рге."},
        {"id": "r4", "type": "transform", "topic": P, "source_ru": "Я в гости́нице.", "task": "Say it about the railway station instead.", "answer": "Я на вокза́ле.", "explanation": "The station takes на, and вокза́л becomes вокза́ле."},
        {"id": "r5", "type": "build", "topic": L, "meaning_en": "My sister is still at the airport.", "tiles": ["Моя́", "сестра́", "ещё", "в", "аэропорту́."], "answer": "Моя́ сестра́ ещё в аэропорту́.", "explanation": "в аэропорту́, with the stressed -у́."},
        {"id": "r6", "type": "choice", "topic": P, "question_ru": "Где апте́ка?", "question_en": "Pick the natural answer.", "options": ["На у́лице Арба́т.", "В у́лица Арба́т.", "На у́лицу Арба́т."], "answer_index": 0, "explanation": "Location: на + prepositional, на у́лице."},
    ]},
    ("listening", 0): {"title": "Listening", "items": [
        {"id": "l1", "type": "listen_choice", "topic": P, "audio_ru": "Я жду вас на вокза́ле.", "question_en": "Where is the speaker waiting?", "options": ["At the station", "At the hotel", "At the airport"], "answer_index": 0, "explanation": "на вокза́ле: at the station."},
        {"id": "l2", "type": "listen_choice", "topic": L, "audio_ru": "Мы ещё в аэропорту́, бу́дем че́рез час.", "question_en": "Where are they now?", "options": ["At the airport", "On the square", "At home"], "answer_index": 0, "explanation": "в аэропорту́: at the airport."},
        {"id": "l3", "type": "dictation", "topic": P, "audio_ru": "Апте́ка на пло́щади.", "translation_en": "The pharmacy is on the square.", "explanation": "на пло́щади, with -и."},
        {"id": "l4", "type": "dictation", "topic": P, "audio_ru": "Мы в гости́нице.", "translation_en": "We're at the hotel.", "explanation": "в гости́нице, with -е."},
    ]},
    ("quiz", 0): {"title": "Quiz", "items": [
        {"id": "z1", "type": "choice", "topic": P, "question_ru": "Он ___ вокза́ле.", "options": ["в", "на"], "answer_index": 1, "explanation": "на вокза́ле."},
        {"id": "z2", "type": "fill", "topic": P, "prompt_ru": "Мы живём в ___.", "cue": "Москва́", "translation_en": "We live in Moscow.", "answer": "Москве́", "explanation": "в Москве́."},
        {"id": "z3", "type": "fill", "topic": L, "prompt_ru": "Я в ___.", "cue": "аэропо́рт", "translation_en": "I'm at the airport.", "answer": "аэропорту́", "explanation": "в аэропорту́, stressed -у́."},
        {"id": "z4", "type": "choice", "topic": P, "question_ru": "Па́па на ___.", "question_en": "Dad is at work.", "options": ["рабо́та", "рабо́те", "рабо́ту"], "answer_index": 1, "explanation": "на рабо́те: location, prepositional."},
        {"id": "z5", "type": "translate", "topic": P, "en": "The hotel is on the square.", "answer": "Гости́ница на пло́щади.", "explanation": "на пло́щади."},
        {"id": "z6", "type": "fill", "topic": P, "prompt_ru": "Встре́тимся на ___.", "cue": "ста́нция", "translation_en": "Let's meet at the station.", "answer": "ста́нции", "explanation": "-ия nouns take -и: на ста́нции."},
        {"id": "z7", "type": "transform", "topic": P, "source_ru": "Я иду́ на ры́нок.", "task": "Say you are already at the market.", "answer": "Я на ры́нке.", "accepted": ["Я уже́ на ры́нке."], "explanation": "на ры́нок (going) becomes на ры́нке (being there)."},
        {"id": "z8", "type": "match", "topic": P, "instruction": "Match each place to 'at/in' it.", "pairs": [
            {"left": "музе́й", "right": "в музе́е"}, {"left": "у́лица", "right": "на у́лице"}, {"left": "парк", "right": "в па́рке"}], "explanation": "в for buildings and parks, на for streets."},
        {"id": "z9", "type": "build", "topic": P, "meaning_en": "We are in the museum now.", "tiles": ["Мы", "сейча́с", "в", "музе́е."], "answer": "Мы сейча́с в музе́е.", "accepted": ["Сейча́с мы в музе́е."], "explanation": "в музе́е."},
        {"id": "z10", "type": "listen_choice", "topic": P, "audio_ru": "Она́ на рабо́те до шести́.", "question_en": "Where is she?", "options": ["At work", "At the market", "In the park"], "answer_index": 0, "explanation": "на рабо́те: at work."},
    ]},
}


def seed_demo(session: Session) -> None:
    """Store the hand-written content for the first unit (idempotent)."""
    from app.services import units

    for (kind, variant), body in DEMO.items():
        units.store(session, DEMO_UNIT, kind, variant, body)
